name: FastAPI CI/CD Workflow

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull request to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Run tests
      run: |
        source venv/bin/activate
        # Here you can add your test command, e.g., pytest
        echo "No tests yet!" # Placeholder for actual test command

    - name: Build Docker image
      run: |
        docker build -t fastapi-todo-app .
    
    - name: Push Docker image to Docker Hub
      if: github.ref == 'refs/heads/main'
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker tag fastapi-todo-app:latest prathamesh1809/fastapi-todo-app:latest
        docker push prathamesh1809/fastapi-todo-app:latest

